// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Verifies user credentials and issues a JWT access token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Authenticate user",
                "parameters": [
                    {
                        "description": "Login Credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "invalid email or password",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/billing/usage": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches real-time transaction, item tracking, and staff identity usage statistics against plan cap thresholds.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billing"
                ],
                "summary": "Get tenant quota consumption",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/billing.UsageResponse"
                        }
                    },
                    "401": {
                        "description": "missing valid tenant validation credentials",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "402": {
                        "description": "plan metric consumption limitation ceiling reached",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "internal service persistence layer failure",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/plans": {
            "get": {
                "description": "Returns a matrix layout of all structural subscription plan capabilities and resource limits.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billing"
                ],
                "summary": "List pricing tier catalogs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/billing.PlanResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error context details",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tenants": {
            "post": {
                "description": "Creates a new business tenant profile along with its initial root admin account.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new tenant",
                "parameters": [
                    {
                        "description": "Signup Details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.SignupRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/auth.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request body / validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "email already registered",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tenants/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves structural information about the authenticated user's tenant account context.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tenancy"
                ],
                "summary": "Get current tenant profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tenancy.TenantResponse"
                        }
                    },
                    "401": {
                        "description": "missing tenant context / unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/customers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all customer profiles matching the active tenant organizational boundary.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sales"
                ],
                "summary": "List tenant customer accounts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/sales.CustomerResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Missing valid tenant validation credentials",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal service database lookup fault",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Registers a new customer account record attached to the current active tenant workspace.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sales"
                ],
                "summary": "Create a new customer profile",
                "parameters": [
                    {
                        "description": "Customer details input parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sales.CreateCustomerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/sales.CustomerResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid payload data syntax or missing required fields",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Missing valid tenant validation credentials",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/orders": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Submits a sales checkout request, consumes monthly plan order entitlement quotas, and runs transactional inventory stock deductions.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sales"
                ],
                "summary": "Place a new sales order",
                "parameters": [
                    {
                        "description": "Order checklist containing items list details mapping",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sales.CreateOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/sales.OrderResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid references or schema entity fields input data validation errors",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Missing valid tenant validation credentials",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Active monthly plan order transaction cap limit exhausted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Order registered but partial stock depletion triggered a fallback state",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/orders/{orderId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches the comprehensive order composition manifest, settlement pricing math summaries, and current routing lifecycle status tags.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sales"
                ],
                "summary": "Get details of a sales order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System transaction reference token lookup ID (UUID)",
                        "name": "orderId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/sales.OrderResponse"
                        }
                    },
                    "400": {
                        "description": "Malformed track sequence path identifier value format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Missing valid tenant validation credentials",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "No transactional invoice matches the specified trace index ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Core data repository extraction execution block runtime failure",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/products": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Provides full product catalog metrics visibility owned by the matching business group profile.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "List catalog tracking records",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/inventory.ProductResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Missing valid tenant validation credentials",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Core relational lookup tracking query fault context",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds a unique tracking product variant profile under the current client scope. Enforces item ceiling controls.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Create a product item",
                "parameters": [
                    {
                        "description": "Product registration data template",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.CreateProductRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/inventory.ProductResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid structural input payload values",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Missing valid tenant validation credentials",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Product catalog resource entitlement quota exhausted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "SKU code entry collision matching active entity records",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/products/{productId}/stock": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns current stock level breakdowns and reorder triggers across all operational warehouse points.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get product stock levels",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target inventory resource look up track key ID (UUID)",
                        "name": "productId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/inventory.StockLevelResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Malformed route identification parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Missing valid tenant validation credentials",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "No item registration matches the requested ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal query execution layer exception structural crash",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/products/{productId}/stock/adjust": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mutates available balance counts up or down across distinct warehouses. Rejects operations that result in a negative total.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Adjust product stock level",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target catalog item system resource ID (UUID)",
                        "name": "productId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Storage destination map and balancing metrics delta values",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.AdjustStockRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/inventory.StockLevelResponse"
                        }
                    },
                    "400": {
                        "description": "Malformed route parameters or tracking payload errors",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Missing valid tenant validation credentials",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Target unique identification index resource missing",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Balancing step rejected because final allocation would fall below zero",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/warehouses": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a full list of storage locations associated with the active tenant.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "List all warehouses",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/inventory.WarehouseResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Missing valid tenant validation credentials",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal service storage lookup engine failure",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deploys a distinct inventory tracking location workspace for the tenant.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Create a new warehouse",
                "parameters": [
                    {
                        "description": "Warehouse creation parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventory.CreateWarehouseRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/inventory.WarehouseResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid payload or request processing error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Missing valid tenant validation credentials",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.AuthResponse": {
            "type": "object",
            "properties": {
                "role": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "auth.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "auth.SignupRequest": {
            "type": "object",
            "properties": {
                "business_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "billing.PlanResponse": {
            "type": "object",
            "properties": {
                "billing_interval": {
                    "type": "string",
                    "x-nullable": true,
                    "example": "monthly"
                },
                "max_orders_per_month": {
                    "type": "integer",
                    "x-nullable": true,
                    "example": 100
                },
                "max_products": {
                    "type": "integer",
                    "x-nullable": true,
                    "example": 50
                },
                "max_users": {
                    "description": "null = unlimited",
                    "type": "integer",
                    "x-nullable": true,
                    "example": 3
                },
                "name": {
                    "type": "string",
                    "example": "free"
                },
                "price_amount": {
                    "type": "number",
                    "example": 0
                },
                "price_currency": {
                    "type": "string",
                    "example": "NGN"
                }
            }
        },
        "billing.UsageResponse": {
            "type": "object",
            "properties": {
                "orders_cap": {
                    "type": "integer",
                    "x-nullable": true,
                    "example": 100
                },
                "orders_used": {
                    "type": "integer",
                    "example": 42
                },
                "plan_name": {
                    "type": "string",
                    "example": "free"
                },
                "products_cap": {
                    "type": "integer",
                    "x-nullable": true,
                    "example": 50
                },
                "products_used": {
                    "type": "integer",
                    "example": 12
                },
                "users_cap": {
                    "type": "integer",
                    "x-nullable": true,
                    "example": 3
                },
                "users_used": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "inventory.AdjustStockRequest": {
            "type": "object",
            "properties": {
                "delta": {
                    "description": "Can be negative (deductions) or positive (restocks)",
                    "type": "integer",
                    "example": 25
                },
                "warehouse_id": {
                    "type": "string",
                    "example": "8f076135-d858-45ec-b9cc-0320df4ee99c"
                }
            }
        },
        "inventory.CreateProductRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Ergonomic Office Chair Premium"
                },
                "sku": {
                    "type": "string",
                    "example": "PROD-XYZ-001"
                }
            }
        },
        "inventory.CreateWarehouseRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Lagos Central Distribution Hub"
                }
            }
        },
        "inventory.ProductResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Ergonomic Office Chair Premium"
                },
                "product_id": {
                    "type": "string",
                    "example": "bc731ee0-3333-4f9e-a89c-a1d257211140"
                },
                "sku": {
                    "type": "string",
                    "example": "PROD-XYZ-001"
                }
            }
        },
        "inventory.StockLevelResponse": {
            "type": "object",
            "properties": {
                "product_id": {
                    "type": "string",
                    "example": "bc731ee0-3333-4f9e-a89c-a1d257211140"
                },
                "quantity": {
                    "type": "integer",
                    "example": 142
                },
                "reorder_point": {
                    "type": "integer",
                    "example": 15
                },
                "warehouse_id": {
                    "type": "string",
                    "example": "8f076135-d858-45ec-b9cc-0320df4ee99c"
                }
            }
        },
        "inventory.WarehouseResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Lagos Central Distribution Hub"
                },
                "warehouse_id": {
                    "type": "string",
                    "example": "8f076135-d858-45ec-b9cc-0320df4ee99c"
                }
            }
        },
        "sales.CreateCustomerRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "johndoe@example.com"
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                }
            }
        },
        "sales.CreateOrderRequest": {
            "type": "object",
            "properties": {
                "customer_id": {
                    "type": "string",
                    "example": "a4b6c8d0-1234-5678-90ab-cdef12345678"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/sales.OrderItemRequest"
                    }
                }
            }
        },
        "sales.CustomerResponse": {
            "type": "object",
            "properties": {
                "customer_id": {
                    "type": "string",
                    "example": "a4b6c8d0-1234-5678-90ab-cdef12345678"
                },
                "email": {
                    "type": "string",
                    "example": "johndoe@example.com"
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                }
            }
        },
        "sales.OrderItemRequest": {
            "type": "object",
            "properties": {
                "product_id": {
                    "type": "string",
                    "example": "bc731ee0-3333-4f9e-a89c-a1d257211140"
                },
                "quantity": {
                    "type": "integer",
                    "example": 2
                },
                "unit_price": {
                    "description": "Client-supplied; no pricing catalog yet",
                    "type": "number",
                    "example": 25000
                },
                "warehouse_id": {
                    "type": "string",
                    "example": "8f076135-d858-45ec-b9cc-0320df4ee99c"
                }
            }
        },
        "sales.OrderItemResponse": {
            "type": "object",
            "properties": {
                "product_id": {
                    "type": "string",
                    "example": "bc731ee0-3333-4f9e-a89c-a1d257211140"
                },
                "quantity": {
                    "type": "integer",
                    "example": 2
                },
                "unit_price": {
                    "type": "number",
                    "example": 25000
                },
                "warehouse_id": {
                    "type": "string",
                    "example": "8f076135-d858-45ec-b9cc-0320df4ee99c"
                }
            }
        },
        "sales.OrderResponse": {
            "type": "object",
            "properties": {
                "customer_id": {
                    "type": "string",
                    "example": "a4b6c8d0-1234-5678-90ab-cdef12345678"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/sales.OrderItemResponse"
                    }
                },
                "order_id": {
                    "type": "string",
                    "example": "d3b07384-d113-4956-953e-52f01f05e3d9"
                },
                "status": {
                    "description": "e.g., pending, fulfilled, stock_issue",
                    "type": "string",
                    "example": "fulfilled"
                },
                "total": {
                    "type": "number",
                    "example": 50000
                }
            }
        },
        "tenancy.TenantResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "OneDesk API",
	Description:      "Multi-tenant REP system for OneDesk.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
